### ISSUE TITLE
Expand Scope to 2.2 FEE

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-kfe-motion#10]
The 2.2 PLC is missing. As a potentially temporary measure we'll be adding the 3 FEE 2.2 devices to this project:

- EK1110 append to PLC rail for the extra port
- Include code for IM1K1, IM2K1, and the zero order stopper
- Include IO, NC for the above

**Comment by ZLLentz** [comment]
Jk we decided not to do this

**Comment by klauer** [comment]
😆
