### ISSUE TITLE
Add solid attenuator AT1K4 axes + program

### ISSUE THREAD

**Issue by klauer** [pcdshub/lcls-plc-kfe-motion#56]
AT1K4, as it's before the stopper ST1K4 belongs in this repo and not in tmo-motion.

![image](https://user-images.githubusercontent.com/5139267/99433306-31d8f280-28c2-11eb-9e1d-aaf2e9cf7fc3.png)

Ref. https://github.com/pcdshub/lcls-plc-tmo-motion/pull/39#issuecomment-729111898

**Comment by ZLLentz** [comment]
I'm also removing the "trap" IO from the tmo plc in https://github.com/pcdshub/lcls-plc-tmo-motion/pull/40

lcls-twincat-motion v1.4.0 is now deployed on the prog node as well
