### ISSUE TITLE
AT1K4 axes are reversed 3 times, making MMS:01 downstream

### ISSUE THREAD

**Issue by klauer** [pcdshub/lcls-plc-kfe-motion#64]
* The attenuator was installed in reverse (the SME later admitted this was a known possibility but did not mention it)
* The axes were wired up in reverse (downstream/upstream were swapped)
* The PLC project was configured to reverse the miswiring

The above 3 things together make it such that the fixed PLC/miswired box/flipped install is *now* inconsistent in what we expect the upstream-most axis to be.

**Comment by ZLLentz** [comment]
:fire:
